name: Publish to Pub.dev

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Publish Package
        run: dart pub publish --force
