name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'

      - name: Accept Android SDK licenses
        run: |
          yes | sdkmanager --licenses
        shell: bash

      - name: Install Android NDK
        run: |
          sdkmanager "ndk;28.0.12433566"
        shell: bash

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Build example app
        run: |
          cd example
          flutter pub get
          flutter build apk --debug
